// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Atomization.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _ATOMIZATION_H_
#define _ATOMIZATION_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Atomization_SOURCE)
#define Atomization_DllAPI __declspec( dllexport )
#else
#define Atomization_DllAPI __declspec( dllimport )
#endif // Atomization_SOURCE
#else
#define Atomization_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Atomization_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure AML_IP_Atom defined by the user in the IDL file.
 * @ingroup ATOMIZATION
 */
class AML_IP_Atom
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AML_IP_Atom();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AML_IP_Atom();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AML_IP_Atom that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atom(
            const AML_IP_Atom& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AML_IP_Atom that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atom(
            AML_IP_Atom&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AML_IP_Atom that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atom& operator =(
            const AML_IP_Atom& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AML_IP_Atom that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atom& operator =(
            AML_IP_Atom&& x);

    /*!
     * @brief This function copies the value in member ucs
     * @param _ucs New value to be copied in member ucs
     */
    eProsima_user_DllExport void ucs(
            const std::vector<uint32_t>& _ucs);

    /*!
     * @brief This function moves the value in member ucs
     * @param _ucs New value to be moved in member ucs
     */
    eProsima_user_DllExport void ucs(
            std::vector<uint32_t>&& _ucs);

    /*!
     * @brief This function returns a constant reference to member ucs
     * @return Constant reference to member ucs
     */
    eProsima_user_DllExport const std::vector<uint32_t>& ucs() const;

    /*!
     * @brief This function returns a reference to member ucs
     * @return Reference to member ucs
     */
    eProsima_user_DllExport std::vector<uint32_t>& ucs();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const AML_IP_Atom& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::vector<uint32_t> m_ucs;
};
/*!
 * @brief This class represents the structure AML_IP_Atomization defined by the user in the IDL file.
 * @ingroup ATOMIZATION
 */
class AML_IP_Atomization
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport AML_IP_Atomization();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~AML_IP_Atomization();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object AML_IP_Atomization that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atomization(
            const AML_IP_Atomization& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object AML_IP_Atomization that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atomization(
            AML_IP_Atomization&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object AML_IP_Atomization that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atomization& operator =(
            const AML_IP_Atomization& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object AML_IP_Atomization that will be copied.
     */
    eProsima_user_DllExport AML_IP_Atomization& operator =(
            AML_IP_Atomization&& x);

    /*!
     * @brief This function copies the value in member atoms
     * @param _atoms New value to be copied in member atoms
     */
    eProsima_user_DllExport void atoms(
            const std::vector<AML_IP_Atom>& _atoms);

    /*!
     * @brief This function moves the value in member atoms
     * @param _atoms New value to be moved in member atoms
     */
    eProsima_user_DllExport void atoms(
            std::vector<AML_IP_Atom>&& _atoms);

    /*!
     * @brief This function returns a constant reference to member atoms
     * @return Constant reference to member atoms
     */
    eProsima_user_DllExport const std::vector<AML_IP_Atom>& atoms() const;

    /*!
     * @brief This function returns a reference to member atoms
     * @return Reference to member atoms
     */
    eProsima_user_DllExport std::vector<AML_IP_Atom>& atoms();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const AML_IP_Atomization& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::vector<AML_IP_Atom> m_atoms;
};

#endif // _ATOMIZATION_H_