// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file service.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_SERVICE_H_
#define _FAST_DDS_GENERATED_SERVICE_H_

#include "status.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(service_SOURCE)
#define service_DllAPI __declspec( dllexport )
#else
#define service_DllAPI __declspec( dllimport )
#endif // service_SOURCE
#else
#define service_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define service_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure ServiceRequest defined by the user in the IDL file.
 * @ingroup SERVICE
 */
class ServiceRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ServiceRequest();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ServiceRequest();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ServiceRequest that will be copied.
     */
    eProsima_user_DllExport ServiceRequest(
            const ServiceRequest& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ServiceRequest that will be copied.
     */
    eProsima_user_DllExport ServiceRequest(
            ServiceRequest&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ServiceRequest that will be copied.
     */
    eProsima_user_DllExport ServiceRequest& operator =(
            const ServiceRequest& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ServiceRequest that will be copied.
     */
    eProsima_user_DllExport ServiceRequest& operator =(
            ServiceRequest&& x);

    /*!
     * @brief Comparison operator.
     * @param x ServiceRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ServiceRequest& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ServiceRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ServiceRequest& x) const;

    /*!
     * @brief This function copies the value in member requester_id
     * @param _requester_id New value to be copied in member requester_id
     */
    eProsima_user_DllExport void requester_id(
            const std::string& _requester_id);

    /*!
     * @brief This function moves the value in member requester_id
     * @param _requester_id New value to be moved in member requester_id
     */
    eProsima_user_DllExport void requester_id(
            std::string&& _requester_id);

    /*!
     * @brief This function returns a constant reference to member requester_id
     * @return Constant reference to member requester_id
     */
    eProsima_user_DllExport const std::string& requester_id() const;

    /*!
     * @brief This function returns a reference to member requester_id
     * @return Reference to member requester_id
     */
    eProsima_user_DllExport std::string& requester_id();
    /*!
     * @brief This function sets a value in member request_id
     * @param _request_id New value for member request_id
     */
    eProsima_user_DllExport void request_id(
            uint32_t _request_id);

    /*!
     * @brief This function returns the value of member request_id
     * @return Value of member request_id
     */
    eProsima_user_DllExport uint32_t request_id() const;

    /*!
     * @brief This function returns a reference to member request_id
     * @return Reference to member request_id
     */
    eProsima_user_DllExport uint32_t& request_id();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const ServiceRequest& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_requester_id;
    uint32_t m_request_id;
};
/*!
 * @brief This class represents the structure ProcessingRequest defined by the user in the IDL file.
 * @ingroup SERVICE
 */
class ProcessingRequest
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ProcessingRequest();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ProcessingRequest();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ProcessingRequest that will be copied.
     */
    eProsima_user_DllExport ProcessingRequest(
            const ProcessingRequest& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ProcessingRequest that will be copied.
     */
    eProsima_user_DllExport ProcessingRequest(
            ProcessingRequest&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ProcessingRequest that will be copied.
     */
    eProsima_user_DllExport ProcessingRequest& operator =(
            const ProcessingRequest& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ProcessingRequest that will be copied.
     */
    eProsima_user_DllExport ProcessingRequest& operator =(
            ProcessingRequest&& x);

    /*!
     * @brief Comparison operator.
     * @param x ProcessingRequest object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ProcessingRequest& x) const;

    /*!
     * @brief Comparison operator.
     * @param x ProcessingRequest object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ProcessingRequest& x) const;

    /*!
     * @brief This function copies the value in member requester_id
     * @param _requester_id New value to be copied in member requester_id
     */
    eProsima_user_DllExport void requester_id(
            const std::string& _requester_id);

    /*!
     * @brief This function moves the value in member requester_id
     * @param _requester_id New value to be moved in member requester_id
     */
    eProsima_user_DllExport void requester_id(
            std::string&& _requester_id);

    /*!
     * @brief This function returns a constant reference to member requester_id
     * @return Constant reference to member requester_id
     */
    eProsima_user_DllExport const std::string& requester_id() const;

    /*!
     * @brief This function returns a reference to member requester_id
     * @return Reference to member requester_id
     */
    eProsima_user_DllExport std::string& requester_id();
    /*!
     * @brief This function sets a value in member request_id
     * @param _request_id New value for member request_id
     */
    eProsima_user_DllExport void request_id(
            uint32_t _request_id);

    /*!
     * @brief This function returns the value of member request_id
     * @return Value of member request_id
     */
    eProsima_user_DllExport uint32_t request_id() const;

    /*!
     * @brief This function returns a reference to member request_id
     * @return Reference to member request_id
     */
    eProsima_user_DllExport uint32_t& request_id();

    /*!
     * @brief This function copies the value in member server_id
     * @param _server_id New value to be copied in member server_id
     */
    eProsima_user_DllExport void server_id(
            const std::string& _server_id);

    /*!
     * @brief This function moves the value in member server_id
     * @param _server_id New value to be moved in member server_id
     */
    eProsima_user_DllExport void server_id(
            std::string&& _server_id);

    /*!
     * @brief This function returns a constant reference to member server_id
     * @return Constant reference to member server_id
     */
    eProsima_user_DllExport const std::string& server_id() const;

    /*!
     * @brief This function returns a reference to member server_id
     * @return Reference to member server_id
     */
    eProsima_user_DllExport std::string& server_id();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const ProcessingRequest& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_requester_id;
    uint32_t m_request_id;
    std::string m_server_id;
};

#endif // _FAST_DDS_GENERATED_SERVICE_H_