// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file status.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_STATUS_H_
#define _FAST_DDS_GENERATED_STATUS_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(status_SOURCE)
#define status_DllAPI __declspec( dllexport )
#else
#define status_DllAPI __declspec( dllimport )
#endif // status_SOURCE
#else
#define status_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define status_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the enumeration NodeKind defined by the user in the IDL file.
 * @ingroup STATUS
 */
enum NodeKind : uint32_t
{
    UNDETERMINED,
    DISCOVERY,
    AGENT,
    MAIN,
    COMPUTATIONAL,
    EDGE
};
/*!
 * @brief This class represents the enumeration StatusKind defined by the user in the IDL file.
 * @ingroup STATUS
 */
enum StatusKind : uint32_t
{
    RUNNING,
    DISABLED
};
/*!
 * @brief This class represents the structure Status defined by the user in the IDL file.
 * @ingroup STATUS
 */
class Status
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Status();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Status();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Status that will be copied.
     */
    eProsima_user_DllExport Status(
            const Status& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Status that will be copied.
     */
    eProsima_user_DllExport Status(
            Status&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Status that will be copied.
     */
    eProsima_user_DllExport Status& operator =(
            const Status& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Status that will be copied.
     */
    eProsima_user_DllExport Status& operator =(
            Status&& x);

    /*!
     * @brief Comparison operator.
     * @param x Status object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Status& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Status object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Status& x) const;

    /*!
     * @brief This function copies the value in member id
     * @param _id New value to be copied in member id
     */
    eProsima_user_DllExport void id(
            const std::string& _id);

    /*!
     * @brief This function moves the value in member id
     * @param _id New value to be moved in member id
     */
    eProsima_user_DllExport void id(
            std::string&& _id);

    /*!
     * @brief This function returns a constant reference to member id
     * @return Constant reference to member id
     */
    eProsima_user_DllExport const std::string& id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport std::string& id();
    /*!
     * @brief This function sets a value in member node_kind
     * @param _node_kind New value for member node_kind
     */
    eProsima_user_DllExport void node_kind(
            NodeKind _node_kind);

    /*!
     * @brief This function returns the value of member node_kind
     * @return Value of member node_kind
     */
    eProsima_user_DllExport NodeKind node_kind() const;

    /*!
     * @brief This function returns a reference to member node_kind
     * @return Reference to member node_kind
     */
    eProsima_user_DllExport NodeKind& node_kind();

    /*!
     * @brief This function sets a value in member status
     * @param _status New value for member status
     */
    eProsima_user_DllExport void status(
            StatusKind _status);

    /*!
     * @brief This function returns the value of member status
     * @return Value of member status
     */
    eProsima_user_DllExport StatusKind status() const;

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport StatusKind& status();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const Status& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    std::string m_id;
    NodeKind m_node_kind;
    StatusKind m_status;
};

#endif // _FAST_DDS_GENERATED_STATUS_H_